version: 0.0
Resources:
  - SAMTemplateStack-VisitorCounterFunction-v1a52Jmm674o:
      Type: AWS::Lambda::Function
      Properties:
        Alias: AWSResumeBackEnd
        CurrentVersion: 1
        TargetVersion: 4
