version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: AWSResumeBackEnd
        Alias: live
        CurrentVersion: 1
        TargetVersion: 2
